grupozeroproject/grupozeroproject/urls.py
# grupozeroproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('storegrupozero.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Incluir URLs de autenticación de Django
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

grupozeroproject/storegrupozero/urls.py
from django.urls import path
from storegrupozero import views
from storegrupozero.views import login_view, registro
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('artistas/', views.artistas, name='artistas'),
    path('tecnicas/', views.tecnicas, name='tecnicas'),
    path('productos/', views.productos, name='productos'),
    path('producto/<int:product_id>/', views.producto_detalle, name='producto_detalle'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('carrito/', views.view_cart, name='view_cart'),
    path('remove_from_cart/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update_cart_item_quantity/<int:item_id>/', views.update_cart_item_quantity, name='update_cart_item_quantity'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('login/', login_view, name='login'),
    path('logout/', views.custom_logout_view, name='logout'),
    path('registro/', registro, name='registro'),
    path('contacto/', views.formulario_contacto, name='contacto'),
    path('contacto/exito/', views.exito, name='exito'),
    path('contacto/error/', views.error, name='error'),
    path('contacto/mensajes/', views.lista_mensajes, name='lista_mensajes'),
]

grupozeroproject/storegrupozero/models.py
from django.contrib.auth.models import User
from django.db import models
from django import forms
from .utils import encrypt_message, decrypt_message

# MODELO ARTISTAS
class Artist(models.Model):
    name = models.CharField(max_length=100)
    bio = models.TextField()
    image = models.ImageField(upload_to='artists/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

# MODELO TECNICAS
class Technique(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='techniques/', null=True, blank=True)  # Agregar campo de imagen
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

# MODELO PRODUCTOS
class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')
    stock = models.PositiveIntegerField(default=1)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='products')
    technique = models.ForeignKey(Technique, on_delete=models.CASCADE, related_name='products')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

# MODELO CARRITO DE COMPRAS
class Cart(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    session_key = models.CharField(max_length=40, null=True, blank=True)
    items = models.ManyToManyField('CartItem', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class CartItem(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    session_key = models.CharField(max_length=40, null=True, blank=True)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

# MODELO PARA INFORMACION CONTACTOS
class MensajeContacto(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField()
    mensaje = models.TextField()
    mensaje_cifrado = models.TextField(blank=True, null=True)
    fecha = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        # Cifra el mensaje antes de guardarlo
        self.mensaje_cifrado = encrypt_message(self.mensaje)
        super().save(*args, **kwargs)

    def get_mensaje(self):
        # Si no hay mensaje cifrado, devolver el mensaje sin cifrar
        if not self.mensaje_cifrado:
            return self.mensaje
        # Descifra el mensaje al recuperarlo
        return decrypt_message(self.mensaje_cifrado)

    def __str__(self):
        return self.nombre

grupozeroproject/storegrupozero/forms.py
# storegrupozero/forms.py
from django import forms
from .models import MensajeContacto
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

#FORMULARIO CONTACTO
class ContactForm(forms.ModelForm):
    class Meta:
        model = MensajeContacto
        fields = ['nombre', 'correo', 'mensaje']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingresa tu nombre'}),
            'correo': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Ingresa tu correo'}),
            'mensaje': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Ingresa tu mensaje', 'rows': 3}),
        }

#FORMULARIO REGISTRO
class RegistroForm(forms.ModelForm):
    email = forms.EmailField(label='Correo', error_messages={
        'required': 'Este campo es obligatorio.',
        'invalid': 'Introduce una dirección de correo electrónico válida.',
    })
    username = forms.CharField(label='Nombre de usuario', max_length=150, error_messages={
        'required': 'Este campo es obligatorio.',
        'max_length': 'El nombre de usuario no puede tener más de 150 caracteres.',
    })
    password = forms.CharField(label='Contraseña', widget=forms.PasswordInput, help_text='La contraseña debe tener al menos 8 caracteres.', error_messages={
        'required': 'Este campo es obligatorio.',
    })

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError('Este correo electrónico ya está en uso.')
        return email

grupozeroproject/storegrupozero/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import ContactForm, RegistroForm
from .models import Artist, Technique, Product, Cart, CartItem, MensajeContacto
import random
from django.contrib.auth.decorators import login_required, user_passes_test

# VISTA INICIO
def index(request):
    products = list(Product.objects.all())
    artists = list(Artist.objects.all())
    techniques = list(Technique.objects.all())

    featured_products = random.sample(products, min(len(products), 4))
    featured_artist = random.choice(artists) if artists else None
    featured_technique = random.choice(techniques) if techniques else None

    context = {
        'featured_products': featured_products,
        'featured_artist': featured_artist,
        'featured_technique': featured_technique,
    }
    
    return render(request, 'index.html', context)

def artistas(request):
    artists = Artist.objects.all()
    return render(request, 'artistas.html', {'artists': artists})

def tecnicas(request):
    techniques = Technique.objects.all()
    return render(request, 'tecnicas.html', {'techniques': techniques})

def productos(request):
    products = Product.objects.all()
    return render(request, 'productos.html', {'products': products})

def producto_detalle(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'producto_detalle.html', {'product': product})

#VISTA REGISTRO
def registro(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            user = authenticate(username=user.username, password=form.cleaned_data['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'Registro exitoso. ¡Bienvenido!')
                return redirect('index')
            else:
                messages.error(request, 'Error en la autenticación después del registro.')
        else:
            messages.error(request, 'Formulario no válido. Por favor, corrige los errores.')
    else:
        form = RegistroForm()
    return render(request, 'registration/registro.html', {'form': form})

#VISTA LOGIN
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('index')  # Redirige a la página principal después del login
        else:
            messages.error(request, 'Usuario o contraseña incorrectos')
    return render(request, 'login.html')

# CRUD CARRITO
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if not request.session.session_key:
        request.session.create()
    cart, created = Cart.objects.get_or_create(user=request.user if request.user.is_authenticated else None, session_key=request.session.session_key)
    cart_item, created = CartItem.objects.get_or_create(product=product, user=request.user if request.user.is_authenticated else None, session_key=request.session.session_key)
    if not created:
        cart_item.quantity += 1
    cart_item.save()

    cart.items.add(cart_item)
    return redirect('view_cart')

def view_cart(request):
    cart, created = Cart.objects.get_or_create(user=request.user if request.user.is_authenticated else None, session_key=request.session.session_key)
    return render(request, 'carrito.html', {'cart': cart})

def remove_from_cart(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id, user=request.user if request.user.is_authenticated else None, session_key=request.session.session_key)
    cart_item.delete()
    return redirect('view_cart')

def update_cart_item_quantity(request, item_id):
    cart_item = get_object_or_404(CartItem, id=item_id, user=request.user if request.user.is_authenticated else None, session_key=request.session.session_key)
    if request.method == 'POST':
        quantity = int(request.POST.get('quantity', 1))
        if quantity > 0:
            cart_item.quantity = quantity
            cart_item.save()
        else:
            cart_item.delete()
    return redirect('view_cart')

#VISTA FORMULARIO CONTACTO
def formulario_contacto(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            mensaje_contacto = MensajeContacto(
                nombre=form.cleaned_data['nombre'],
                correo=form.cleaned_data['correo'],
                mensaje=form.cleaned_data['mensaje']
            )
            mensaje_contacto.save()
            messages.success(request, 'Mensaje enviado con éxito.')
            return redirect('exito')
        else:
            messages.error(request, 'Error al enviar el mensaje. Por favor, inténtalo de nuevo.')
            return redirect('error')
    else:
        form = ContactForm()
    return render(request, 'mycontacto/formulario_contacto.html', {'form': form})

# Verificar si el usuario es superusuario
def is_superuser(user):
    return user.is_superuser

# Vista para listar los mensajes
@login_required
@user_passes_test(is_superuser)
def lista_mensajes(request):
    mensajes = MensajeContacto.objects.all()
    mensajes_descifrados = [{'nombre': mensaje.nombre, 'correo': mensaje.correo, 'mensaje': mensaje.get_mensaje(), 'fecha': mensaje.fecha} for mensaje in mensajes]
    return render(request, 'mycontacto/lista_mensajes.html', {'mensajes': mensajes_descifrados})

def exito(request):
    return render(request, 'mycontacto/exito.html')

def error(request):
    return render(request, 'mycontacto/error.html')

@require_POST
def update_cart(request):
    item_id = request.POST.get('item_id')
    quantity = int(request.POST.get('quantity'))
    
    print(f"Updating cart item: {item_id} with quantity: {quantity}")

    try:
        cart_item = CartItem.objects.get(id=item_id, user=request.user if request.user.is_authenticated else None, session_key=request.session.session_key)
        cart_item.quantity = quantity
        cart_item.save()
        
        subtotal = cart_item.product.price * quantity
        cart = Cart.objects.get(items=cart_item)
        total = sum(item.product.price * item.quantity for item in cart.items.all())
        
        print(f"New subtotal: {subtotal}, New total: {total}")

        return JsonResponse({
            'status': 'success',
            'subtotal': subtotal,
            'total': total
        })
    except CartItem.DoesNotExist:
        print("CartItem does not exist")
        return JsonResponse({'status': 'error', 'message': 'Item not found'}, status=400)
    
def custom_logout_view(request):
    logout(request)
    return render(request, 'registration/logged_out.html')

grupozeroproject/storegrupozero/templates/mycontacto/error.html
{% extends "base.html" %}

{% block title %}
Error - Grupo Cero
{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">
    <h2 class="titulo-seccion text-center mb-4">¡Hubo un Error al Enviar el Mensaje!</h2>
    <p class="text-center">Por favor, intenta nuevamente.</p>
    <div class="text-center">
        <a href="{% url 'contacto' %}" class="btn btn-danger">Volver al Formulario</a>
    </div>
</div>
{% endblock %}

grupozeroproject/storegrupozero/templates/mycontacto/exito.html
{% extends "base.html" %}

{% block title %}
Éxito - Grupo Cero
{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">
    <h2 class="titulo-seccion text-center mb-4">¡Mensaje Enviado con Éxito!</h2>
    <p class="text-center">Gracias por contactarnos. Nos pondremos en contacto contigo a la brevedad.</p>
    <div class="text-center">
        <a href="{% url 'index' %}" class="btn btn-primary">Volver al Inicio</a>
    </div>
</div>
{% endblock %}

grupozeroproject/storegrupozero/templates/mycontacto/formulario_contacto.html
{% extends "base.html" %}

{% block title %}
Formulario de Contacto - Grupo Cero
{% endblock %}

{% block body_class %}
fondo-contacto
{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">
    <h2 class="titulo-seccion text-center mb-4 text-white">FORMULARIO DE CONTACTO</h2>
    <form id="formularioContacto" method="post" class="formulario d-flex flex-column align-items-center text-white p-5 rounded">
        {% csrf_token %}
        <div class="container-fluid mb-3 mt-5">
            <div class="row justify-content-center">
                <div class="form col-sm-12 col-md-6 col-lg-4">
                    <label for="id_nombre" class="form-label">Nombre</label>
                    {{ form.nombre }}
                    <div id="errorNombre" class="text-danger"></div>
                </div>
                <div class="form col-sm-12 col-md-6 col-lg-4">
                    <label for="id_correo" class="form-label">Correo</label>
                    {{ form.correo }}
                    <div id="errorCorreo" class="text-danger"></div>
                </div>
            </div>
        </div>
        <div class="container-fluid mb-3">
            <div class="row justify-content-center">
                <div class="form col-12 col-lg-8">
                    <label for="id_mensaje" class="form-label">Mensaje</label>
                    {{ form.mensaje }}
                    <div id="errorMensaje" class="text-danger"></div>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-lg btn-success mt-5">Enviar</button>
    </form>
</div>
{% endblock %}

grupozeroproject/storegrupozero/templates/mycontacto/lista_mensajes.html
<!-- templates/mycontacto/lista_mensajes.html -->
{% extends "base.html" %}

{% block title %}
Lista de Mensajes - Grupo Cero
{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">
    <h2 class="titulo-seccion text-center mb-4">Lista de Mensajes</h2>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Correo</th>
                    <th>Mensaje</th>
                    <th>Fecha</th>
                </tr>
            </thead>
            <tbody>
                {% for mensaje in mensajes %}
                <tr>
                    <td>{{ mensaje.nombre }}</td>
                    <td>{{ mensaje.correo }}</td>
                    <td>{{ mensaje.mensaje }}</td>
                    <td>{{ mensaje.fecha }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}